<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../../package.props"/>
    <Import Project="../../version.props"/>
    <ItemGroup>
        <PackageReference Include="MessagePack" Version="3.1.7" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
        <PackageReference Include="NetTopologySuite" Version="2.6.0" />
        <PackageReference Include="NetTopologySuite.Features" Version="2.2.0" />
        <PackageReference Include="ProjNET" Version="2.1.0" />
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.9" />
<!--        <PackageReference Include="System.Net.Http" Version="4.3.4" />-->
<!--        <PackageReference Include="System.Text.Json" Version="9.0.10" />-->
        <PackageReference Include="Dapper" Version="2.1.79" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
        <PackageReference Include="MongoDB.Bson" Version="3.9.0" />
    </ItemGroup>
    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
            <_Parameter1>ZServer.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Infrastructure\proj.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <None Remove="Infrastructure\esri_proj.csv" />
        <EmbeddedResource Include="Infrastructure\esri_proj.csv" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\ZMap.TileGrid\ZMap.TileGrid.csproj"/>
    </ItemGroup>
    <ItemGroup>
      <Compile Update="RasterLayer.cs">
        <DependentUpon>Layer.cs</DependentUpon>
      </Compile>
      <Compile Update="TiledLayer.cs">
        <DependentUpon>Layer.cs</DependentUpon>
      </Compile>
      <Compile Update="VectorLayer.cs">
        <DependentUpon>Layer.cs</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
