name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    env:
      PGDATABASE: zserver_dev
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres
    services:
      postgres:
        image: postgis/postgis:16-3.5
        ports:
          - 5432/tcp
        options: >-
          -e POSTGRES_DB=zserver_dev
          -e POSTGRES_USER=postgres
          -e POSTGRES_PASSWORD=postgres
          -e PGDATABASE=zserver_dev
          -e PGUSER=postgres
          -e PGPASSWORD=postgres
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --entrypoint sh
          postgis/postgis:16-3.5
          -c "exec docker-entrypoint.sh postgres -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: dotnet build
      - name: Test
      # see https://learn.microsoft.com/en-us/dotnet/api/microsoft.build.framework.loggerverbosity?view=msbuild-17-netcore
        run: dotnet test --no-build --verbosity normal
  
  publish-docker-image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Login docker regsitry
        run: docker login -u ${{ secrets.DOCKER_USER }} -p  ${{ secrets.DOCKER_USER_PASSWORD }}
      - name: Build the Docker image
        run: docker build --target zserver-api -f API.Dockerfile -t zlzforever/zserver-api:202504-1 .
      - name: Publish the Docker image
        run: docker push zlzforever/zserver-api:202504-1
